# GitHub Pages configuration for M2O Support
title: M2O Support
description: Get help with your M2O app experience
url: "https://yourusername.github.io"
baseurl: "/Tweet-iOS"

# Build settings
theme: jekyll-theme-cayman
plugins:
  - jekyll-relative-links

# Exclude from processing
exclude:
  - README.md
  - LICENSE
  - .gitignore
  - Sources/
  - Tweet.xcodeproj/
  - Pods/
  - FFmpeg-iOS/
  - scratch/
  - build/
  - ffmpeg-6.1/
  - *.sh
  - *.md
  - *.txt
  - *.log
